import type { Metadata } from "next";
import "./globals.scss";
import ClientThemeProvider from "@/app/components/theme/ClientThemeProvider";
import ClientLanguageProvider from '@/app/components/lang/ClientLanguageProvider'
// import React components
import dynamic from "next/dynamic"
// import Components
const Header = dynamic(()=> import('@/app/components/header/Header'))
const Footer = dynamic(()=> import('@/app/components/footer/Footer'))

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const direction = params.lang === "ar" ? "rtl" : "ltr";

  return (
    <html lang={params.lang} dir={direction}>
      <body>
        <ClientThemeProvider>
          <ClientLanguageProvider>
            <Header />
            {children}
            <Footer />
            </ClientLanguageProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
